# Generated by Django 4.1.3 on 2024-01-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_client_id', models.IntegerField(blank=True, null=True)),
                ('user_client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('allocate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('site_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('imageName', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('imageName', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('HOME INTERIOR', 'HOME INTERIOR'), ('RETAIL SHOP', 'RETAIL SHOP')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('sac', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_category', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, choices=[('SQR METER', 'SQR METER'), ('MILI METER', 'MILI METER'), ('INCH', 'INCH'), ('SQR FOOT', 'SQR FOOT'), ('RUNNING FOOT', 'RUNNING FOOT'), ('NUMBERS', 'NUMBERS'), ('APPROXIMATE', 'APPROXIMATE'), ('LUMPSUM', 'LUMPSUM')], max_length=100, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('numbers', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('running_foot', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('specifications', models.CharField(blank=True, max_length=500, null=True)),
                ('costing', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, default='20', max_length=100, null=True)),
                ('user_client', models.CharField(blank=True, max_length=100, null=True)),
                ('user_client_id', models.IntegerField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_address', models.CharField(blank=True, max_length=100, null=True)),
                ('client_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('special_note', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('total_with_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date', models.CharField(blank=True, default='17/01/24', max_length=100, null=True)),
                ('revision_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_category', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('costing', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('numbers', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('running_foot', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True)),
                ('specifications', models.CharField(blank=True, max_length=500, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.quotation')),
            ],
        ),
    ]
