# Generated by Django 4.1.3 on 2024-01-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.CharField(blank=True, default='19/01/24', max_length=100, null=True),
        ),
    ]
