# Generated by Django 4.1.3 on 2024-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.CharField(blank=True, default='20/01/24', max_length=100, null=True),
        ),
    ]
