# Generated by Django 4.2.8 on 2024-02-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_alter_enquire_status'),
        ('api', '0007_alter_quotation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiry.enquire'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.CharField(blank=True, default='01/02/24', max_length=100, null=True),
        ),
    ]
