# Generated by Django 4.1.3 on 2024-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_useraccount_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_execution_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_execution_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_sales_and_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
