# Generated by Django 4.1.3 on 2024-01-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='floor_plain',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/'),
        ),
    ]
