# Generated by Django 4.1.3 on 2024-01-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_alter_design_image_alter_enquire_floor_plain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='user',
        ),
        migrations.AddField(
            model_name='design',
            name='enquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enquiry.enquire'),
            preserve_default=False,
        ),
    ]
