# Generated by Django 4.1.3 on 2024-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_remove_design_user_design_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
