# Generated by Django 4.1.3 on 2024-01-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_alter_design_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Prospect', 'Prospect'), ('Clinet', 'Clinet')], default='Enquiry', max_length=20),
        ),
    ]
