# Generated by Django 4.1.3 on 2024-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_enquire_created_by_alter_enquire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Prospect', 'Prospect'), ('Client', 'Client')], default='Enquiry', max_length=20),
        ),
    ]
