# Generated by Django 4.1.3 on 2024-01-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_rename_status_stepsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtitlestructuralwork',
            name='img',
            field=models.FileField(upload_to='structural_work_images/'),
        ),
        migrations.AlterField(
            model_name='stepsmodel',
            name='model_name',
            field=models.CharField(choices=[('PROJECT_START', 'Project Start'), ('STRUCTURAL_WORK', 'Structural Work'), ('LAMINATE_WORK', 'Laminate Work'), ('HARDWARE_INSTALL', 'Hardware Installation'), ('FURNISHING_WORK', 'Furnishing Work'), ('HAND_OVER_AND_FINALIZING', 'Hand Over and Finalizing')], default='PROJECT_START', max_length=50),
        ),
    ]
