# Generated by Django 4.1.3 on 2024-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_alter_imgtitlestructuralwork_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepsmodel',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('NOT_DONE', 'NOT_DONE')], default='NOT_DONE', max_length=50),
        ),
    ]
