# Generated by Django 4.1.3 on 2024-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_stepsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtitlestructuralwork',
            name='img',
            field=models.FileField(upload_to='execution_work_images/'),
        ),
    ]
